name: "Explyt SAST Analyze java projects"

description: "This actions automatically detects java build system, build project and analyze it with ExplytSAST analyzer"

branding:
  icon: 'coffee'
  color: 'red'

inputs:
  projectRoot:
    description: "Path to project root with build.gradle or pom.xml file"
    required: true



runs:
  using: 'composite'
  steps:
    - name: Run analyse task
      uses: explyt/sast-action/analyze@main
      env:
        ANALYZE_PROJECT_ROOT: "xxx___${{inputs.projectRoot}}___xxx"

    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{inputs.projectRoot}}/report-ifds.sarif